name: raha_hr
description: >
  منصة رقمية متقدمة لإدارة الموارد البشرية وتقديم الحلول الذكية المتكاملة
  لدعم قطاع الخدمات والعمالة بالسودان.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  rxdart: ^0.27.7 
  flutter_localizations:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.0
  flutter_local_notifications: ^16.0.0

  http: ^1.1.0
  googleapis_auth: ^1.4.1

  google_sign_in: ^6.1.4
  google_fonts: ^6.1.0
  url_launcher: ^6.1.11
  
  # تم تحديثه ليطابق متطلبات flutter_localizations
  intl: ^0.20.2
  
  geolocator: ^9.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.5.0

  shared_preferences: ^2.2.1
  
  syncfusion_flutter_signaturepad: ^21.1.35
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Aljazeera
      fonts:
        - asset: assets/fonts/Aljazeera.ttf
    - family: ArabicFont
      fonts:
        - asset: assets/fonts/Ar.ttf
  assets:
    - assets/images/hero_bg.jpg
    - assets/images/logo.png
    - assets/service-account.json
