// File generated by FlutLab and modified for Raha project.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android; // تم التعديل هنا ليدعم أندرويد مباشرة
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // بيانات مشروع راحة من ملف google-services.json الخاص بك
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAyRU4DGxJ56pEiNBkp5cVg5RPORvio6Ls",
    appId: "1:510788454430:android:c8f7e31350e6c64b4d860f",
    messagingSenderId: "510788454430",
    projectId: "raha-sd",
    storageBucket: "raha-sd.firebasestorage.app",
  );

  // ملاحظة: إذا كنت تستخدم الويب أيضاً، يفضل تحديث بيانات الويب من الكونسول
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAyRU4DGxJ56pEiNBkp5cVg5RPORvio6Ls",
    appId: "1:510788454430:web:c8f7e31350e6c64b4d860f", // مثال تقريبي للويب
    messagingSenderId: "510788454430",
    projectId: "raha-sd",
    authDomain: "raha-sd.firebaseapp.com",
    storageBucket: "raha-sd.firebasestorage.app",
  );
}
